---
- hosts: prod
  become: yes
  tasks:
    - name: Stop any existing container
      command: docker stop bankapp || true
      ignore_errors: yes

    - name: Remove any existing container
      command: docker rm bankapp || true
      ignore_errors: yes

    - name: Pull the Docker image
      docker_image:
        name: "s2003n/bankapp:latest"
        source: pull

    - name: Run the application container
      docker_container:
        name: bankapp
        image: "s2003n/bankapp:latest"
        ports:
          - "8084:8081"
        restart_policy: always
        detach: yes